### ISSUE TITLE
Allow to get email from vk.com

### ISSUE THREAD

**Issue by is-blackhole** [dgrabla/opauth-vkontakte#3]
Some time ago vk.com allowed sites to get user email if permissions are granted. vk.com sends email within https://oauth.vk.com/access_token together with access_token and user id. How about adding support for email? This code in VKontakteStrategy::int_callback method will do

```
if (!empty($results['email'])) $this->auth['info']['email'] = $results['email'];
```

**Comment by dgrabla** [comment]
Please pull-request

**Comment by dgrabla** [comment]
Thanks
